In [1]:
from cmp import *
% matplotlib notebook

In [2]:
# Inputs

# Lattice vectors (3 vectors of length 3)
a = 1
b = 2
a1 = np.array([1, 0, 0])
a2 = np.array([0, 1, 0])
a3 = np.array([0, 0, 1])
theta = 80*np.pi/180

# Array of basis vectors
basis = np.array([[0,0,0],[0.5,0.5,0],[0.5,0,0.5],[0,0.5,0.5]])
# Colors for each of the basis vectors
colors = ('xkcd:cement','b','b','b')
# Size multiplier for each of the atoms. Default is 1
sizes = (2,1,1,1)


# Gridline type:
# Hard: lines along cartesian axes at integer spacings
# Soft: Lines along cartesian axes. Takes into account nonequal lattice spacing
# LatticeVectors: Lines along the latticevectors (only on lattice points)
GridType = "lattice"

# Limit type:
# Hard: Sets a hard limit on the plotting boundary (default  x = y = z = [0,2])
# Dynamic: Sets the limits as max(nx*a1,ny*a2,nz*a3), so we include nx unitcells in the a1 direction, etc.
# WDynamic: Sets the limits r_min = n_min*[a1 a2 a3] and likewise for n_max
LimType = "wdynamic"
Maxs = [2,2,2]
Mins = [0,0,0]

#LatticeCreator(a1,a2,a3,basis,colors,sizes,LimType,GridType,Mins,Maxs)

In [3]:
#LatticeCreator(Lattice="conventional bcc", colors=["xkcd:cement","b","b","b"])

In [4]:
LatticeTester()

Test done. If nothing printed, all were succesfully classified


In [5]:
lattice, basis = LatticeChooser(lattice_name = "conventional fcc")
# lattice = np.array([[2,0,0],[0,3,0],[0,0,4]])
a1, a2, a3 = lattice

R = RotMatrix()
rLattice = (R@lattice.T).T
rBasis = (R@basis.T).T
rBasis = rBasis[1:]
rLattice = rLattice[[1,2,0]]
mag_lattice = mag(rLattice)
mag_basis = mag(rBasis)
lengthEq = np.isclose(np.sqrt(2) / 2, mag_basis).all()
normalizer = np.outer(mag_lattice, mag_basis)
print(normalizer)
angles = rLattice.dot(rBasis) / normalizer
rank = np.linalg.matrix_rank(angles)
# get angles that are sqrt(2)/2 and 0 respectively
num_sqrt2 = np.isclose(angles, np.sqrt(2) / 2)
num_0 = np.isclose(angles, 0)

# Check whether there are 2 or 1 of these per row
# respectively
num_sqrt2_true = (num_sqrt2.sum(axis=1) ==
                  np.array([2, 2, 2])).all()
num_0_true = (num_0.sum(axis=1) ==
              np.array([1, 1, 1])).all()
anglesEq = rank == 3 and num_0_true and num_sqrt2_true
print(anglesEq)

[[0.70710678 0.70710678 0.70710678]
 [0.70710678 0.70710678 0.70710678]
 [0.70710678 0.70710678 0.70710678]]
True


In [6]:
LatticeTester()


Test done. If nothing printed, all were succesfully classified
