In [2]:
from cmp import *
import pdir
%matplotlib qt

In [3]:
# Control variables

plot_lattice_unfinished_1 = True
plot_lattice_unfinished_2 = True
plot_lattice_demo = True
plot_lattice_planes = True
plot_scattering_none = True
plot_scattering_systemic = True
plot_band_structure_none = True
plot_band_structure_strong = True
plot_nearly_free_band = True


### Lattice with unfinished unit cells

In [40]:
if plot_lattice_unfinished_1:
    a1, a2, a3 = np.eye(3)
    basis = np.array([[0, 0, 0],
                      [0.5, 0.5, 0.5]])

    colors = ['xkcd:cement', 'b']
    sizes = [2, 2]
    grid_type = "latticevectors"
    type_ = "primitive"
    n_min = np.array([0, 0, 0])
    n_max = np.array([1, 1, 1])


    (atomic_positions, lattice_coefficients, atomic_colors, atomic_sizes, 
     lattice_position) = lattices.generator(a1, a2, a3, basis, colors, sizes,
                                            n_min, n_max)
    # Create the figure
    fig = plt.figure(figsize=(2,2))
    ax = fig.gca(projection="3d")

    # Plot atoms
    ax.scatter(atomic_positions[:, 0], atomic_positions[:, 1],
               atomic_positions[:, 2], c=atomic_colors, s=atomic_sizes)

    # Get the relevant gridlines:
    g_col = 'k'
    g_w = 0.5
    pruned_lines = lattices.grid_lines(a1, a2, a3, atomic_positions,
                                       lattice_position, grid_type)
    for line in pruned_lines:
        ax.plot(line[0], line[1], line[2], color=g_col, linewidth=g_w)

    ax.set_aspect('equal')
    ax.set_proj_type('ortho')
    ax.grid(False)
    ax.axis('off')

    # make the panes transparent (the plot box)
    ax.xaxis.set_pane_color((1.0, 1.0, 1.0, 0.0))
    ax.yaxis.set_pane_color((1.0, 1.0, 1.0, 0.0))
    ax.zaxis.set_pane_color((1.0, 1.0, 1.0, 0.0))
    
    ax.view_init(15, -60)
    fig.subplots_adjust(left=-0.15, right=1.15, top=1.15, bottom=-0.15)
    fig.savefig('thesis/figures/lattice_unfinished_1.pdf')

### Lattice with unfinished unit cells 2

In [41]:
if plot_lattice_unfinished_2:
    a1, a2, a3 = np.array([[0.5, 0.5, 0],
                           [0.5, 0, 0.5],
                           [0, 0.5, 0.5]])
    basis = np.array([0, 0, 0])

    colors = ['xkcd:cement']
    sizes = [1]
    grid_type = "latticevectors"
    type_ = "primitive"
    n_min = np.array([0, 0, 0])
    n_max = np.array([2, 2, 2])


    (atomic_positions, lattice_coefficients, atomic_colors, atomic_sizes, 
     lattice_position) = lattices.generator(a1, a2, a3, basis, colors, sizes,
                                            n_min, n_max)
    # Create the figure
    fig = plt.figure(figsize=(2,2))
    ax = fig.gca(projection="3d")

    # Plot atoms
    ax.scatter(atomic_positions[:, 0], atomic_positions[:, 1],
               atomic_positions[:, 2], c=atomic_colors, s=atomic_sizes)

    # Get the relevant gridlines:
    g_col = 'k'
    g_w = 0.3
    pruned_lines = []
    r_min, r_max = 0, 2
    for nx in range(n_min[0], n_max[0] + 1):
        for ny in range(n_min[1], n_max[1] + 1):
            pruned_lines.append([np.array([nx, nx]),
                                 np.array([ny, ny]),
                                 np.array([r_min, r_max])])
        
        for nz in range(n_min[2], n_max[2] + 1):
            pruned_lines.append([np.array([nx, nx]),
                                 np.array([r_min, r_max]),
                                 np.array([nz, nz])])

    for ny in range(n_min[1], n_max[1] + 1):
        for nz in range(n_min[2], n_max[2] + 1):
            pruned_lines.append([np.array([r_min, r_max]),
                                 np.array([ny, ny]),
                                 np.array([nz, nz])])
    for line in pruned_lines:
        ax.plot(line[0], line[1], line[2], color=g_col, linewidth=g_w)

    ax.set_aspect('equal')
    ax.set_proj_type('ortho')
    ax.grid(False)
    ax.axis('off')

    # make the panes transparent (the plot box)
    ax.xaxis.set_pane_color((1.0, 1.0, 1.0, 0.0))
    ax.yaxis.set_pane_color((1.0, 1.0, 1.0, 0.0))
    ax.zaxis.set_pane_color((1.0, 1.0, 1.0, 0.0))
    
    ax.view_init(15, -100)
    
    fig.subplots_adjust(left=-0.2, right=1.2, top=1.2, bottom=-0.2)
    fig.savefig('thesis/figures/lattice_unfinished_2.pdf')

### Demo of proper lattice

In [8]:
if plot_lattice_demo:
    fig, ax = Lattice(lattice_name="conventional bcc", sizes=1,
                      colors=['xkcd:cement', 'b'], returns=True)
    margin = 0.2
    fig.set_size_inches(2,2)
    fig.subplots_adjust(left=-margin, right=1+margin, top=1+margin, bottom=-margin)
    ax.view_init(10, -80)
    fig.savefig('thesis/figures/lattice_demo_1.pdf')
    
    fig, ax = Lattice(lattice_name="hexagonal", sizes=1,
                      returns=True)
    margin = 0.2
    fig.set_size_inches(2,2)
    fig.subplots_adjust(left=-margin, right=1+margin, top=1+margin, bottom=-margin)
    ax.view_init(18, -84)
    fig.savefig('thesis/figures/lattice_demo_2.pdf')

### Family of lattice planes

In [8]:
if plot_lattice_planes:
    fig, ax = Reciprocal(lattice_name="bcc", indices=(0,0,1), max_=(0,0,4), returns=True)
    ax.view_init(10, -80)
    margin = 0.2
    fig.set_size_inches(2,2)
    fig.subplots_adjust(left=-margin, right=1+margin, top=1+margin, bottom=-margin)
    fig.savefig('thesis/figures/lattice_planes_1.pdf')

(0, 0, 1)
[1. 0. 0.] [0. 1. 0.] [0.5 0.5 0.5]
[ 6.28318531  0.         -6.28318531] [ 0.          6.28318531 -6.28318531] [ 0.          0.         12.56637061]
[0.  0.  0.5]


### Scattering!

In [6]:
if plot_scattering_none:
    fig, ax, ax2 = Scattering(basis=np.array([[0, 0, 0],
                                              [0.5, 0.5, 0],
                                              [0.5, 0, 0.5],
                                              [0, 0.5, 0.5]]),
                              form_factor=np.array([1, 0.5, 0.5, 0.5]),
                              highlight=[1,1,2],
                              returns=True)
    ax.view_init(5, -50)
    fig.savefig('thesis/figures/scattering_no_systemic.pdf')

if plot_scattering_systemic:
    fig, ax, ax2 = Scattering(basis=np.array([[0, 0, 0],
                                              [0.5, 0.5, 0],
                                              [0.5, 0, 0.5],
                                              [0, 0.5, 0.5]]),
                              form_factor=np.array([1, 1, 1, 1]),
                              returns=True)
    ax.view_init(5, -55)
    fig.savefig('thesis/figures/scattering_systemic.pdf')

/home/niko/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:29: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims)


There is no scattering for this choice of k_in


### Band structures

In [4]:
if plot_band_structure_none:
    fig, ax, ax2 = Band_structure(edges=True, returns=True)
    ax.view_init(33, -48)
    fig.savefig('thesis/figures/band_structure_none.pdf')
if plot_band_structure_strong:
    fig, ax, ax2 = Band_structure(edges=True, V0=1, returns=True)
    ax.view_init(33, -48)
    fig.savefig('thesis/figures/band_structure_strong.pdf')

In [36]:
import itertools
def calc_1D_band_structure(V0=0, n_k=101, G_range=list(range(-3,4)),
                           potential=band_structure.VG_dirac, extra=0.1):
    kx = np.linspace(-1 / 2 - extra, 1 / 2 + extra, n_k)
    ky = np.linspace(-1 / 2 - extra, 1 / 2 + extra, n_k)
    num_Gs = (len(G_range))**2
    # First we create the relevant matrix for some k:
    b1 = np.array([1, 0])
    b2 = np.array([0, 1])

    ms = np.array(list(itertools.product(G_range, G_range)))
    recip = np.array([b1, b2])
    Gs = ms @ recip
    E = np.zeros((num_Gs, n_k))
    VG_mat = band_structure.potential_matrix(range_=G_range, potential=potential, V0=V0)
    kxs, kys = np.meshgrid(kx, ky)
    for i in range(n_k):
        k = np.array([kx[i], 0])
        Diag = np.diag(lattices.mag(k - Gs)**2) / 2
        Full = Diag + VG_mat
        Eigs = np.linalg.eigvalsh(Full)
        E[:, i] = Eigs

    band_to_return = E[0]


    return kx, band_to_return


if plot_nearly_free_band:
    n_k = 201
    G = 3
    extra = 0.05
    o1 = calc_1D_band_structure(V0=0,
                                n_k=n_k,
                                G_range=list(range(-G,G+1)),
                                extra=0)
    k_free, E_free = o1
    
    o2 = calc_1D_band_structure(V0=0.05,
                                n_k=n_k,
                                G_range=list(range(-G,G+1)),
                                extra=extra)
    k_small, E_small = o2
    
    E_small = E_small - np.amin(E_small)
    fig = plt.figure()
    ax = fig.gca()
    fig.set_size_inches([2,2])
    ax.set_xlabel('$k$')
    ax.set_xticks([-np.pi, 0, np.pi])
    ax.set_xticklabels(['$-\pi/a$', '0', '$\pi/a$'])
    ax.set_yticks([])
    ax.set_ylabel('$E$')
    ax.plot(k_free * 2 * np.pi, E_free, '--')
    ax.plot(k_small * 2 * np.pi, E_small)
    
    
    fig.tight_layout()
    
    fig.savefig('thesis/figures/nearly_free.pdf')